<?php

use Illuminate\Database\Seeder;

class RecomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recoms')->insert([
        	[
                'filter'=>'eat',
                'img'=>'23244290_2001587553450007_6387881263362810140_n.jpg',
                'title'=>'Liu Chu Fang - Hot Pot Buffet & Hong Kong Dimsum',
                'address'=>'56 Nguyen Chi Thanh Street , Hai Chau District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'33964517_1398589076951378_6214767490619146240_n.jpg',
                'title'=>'Đặc sản Hoàng Tín - 12 Lê Hồng Phong',
                'address'=>'12 Lê Hồng Phong, P. Phước Ninh,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'33121516_1753476611378020_3190317946740146176_n.jpg',
                'title'=>'HongDae Korean BBQ & Beer-Đà Nẵng',
                'address'=>'45 Le Hong Phong, Hai Chau District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'28059494_1763007274008153_6850750750335084213_n.jpg',
                'title'=>'BBQ Ủn In - Smoked Pork Ribs',
                'address'=>'379 Tran Hung Dao Street, Son Tra District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'31398119_367118910449079_2368577028115922944_n.jpg',
                'title'=>'1986 restaurant',
                'address'=>'149 Hai Phong , Thanh Khe District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'33750322_193699231263997_996128024044765184_n.jpg',
                'title'=>'Ut Tich coffee',
                'address'=>'73 Nguyen Thai Hoc Street , Hai Chau District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'33580915_256737498225506_5818949742775762944_n.jpg',
                'title'=>'La Maison Deli Cafe & Restaurant',
                'address'=>'Lot A1-2-3, 2 tháng 9 Street, Hai Chau District, Da Nang',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'32954324_257114531502219_7028897946238189568_n.jpg',
        		'title'=>'Nơm Bistro - Essential Vietnamese Cuisine',
        		'address'=>'Lot A1-04, The Villa of Green Island, Hai Chau District, Da Nang',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'32919018_447075869087537_7040595878079365120_n.jpg',
        		'title'=>'Little Orient Bisro',
        		'address'=>'6 Thanh Thuy Street, Hai Chau District, Da Nang',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'eat',
                'img'=>'31703741_1050373805112484_3646985837750517760_n.jpg',
        		'title'=>'Chu Chu - Korean Restaurant',
        		'address'=>'18 Yen Bai Street, Hai Chau District, Da Nang',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-banh-uot-nong-da-nang-140620021159.jpg',
        		'title'=>'The Top Bar - À La Carte Da Nang Beach Hotel',
        		'address'=>'200 Võ Nguyên Giáp,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-n-du-jpg-864-636219870599870164.jpg',
        		'title'=>'Money Milkteaa & Coffee',
        		'address'=>'17 Nguyễn Du,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-960x550-gong-cha-dn--528-636403074352913575.jpg',
        		'title'=>'Gong Cha - 貢茶 - Nguyễn Văn Linh',
        		'address'=>'25 - 29 Nguyễn Văn Linh,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-960x600-vevy-jpg-424-636302840656386464.jpg',
        		'title'=>'Vevy Milktea',
        		'address'=>'71 - 73 Phan Châu Trinh,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-m-sh-jpg-922-636402187208216900.jpg',
        		'title'=>'Sky21 Bar - Belle Maison Parosand Danang Hotel',
        		'address'=>'Tầng 21, Belle Maison Parosand Danang Hotel, 216 Võ Nguyên Giáp,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-a4yh69op-jpg-243-636161138815882499.jpg',
        		'title'=>'The City Pub - Bờ Sông Hàn',
        		'address'=>'92 Bạch Đằng,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-nv-jpg-872-636069451979925431.jpg',
        		'title'=>'Never Mind - Top Bar & Coffee',
        		'address'=>'Tầng 15, Golden Sea 3 Hotel, 242 Võ Nguyên Giáp,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-slide_92-jpg-179-635665882226952895.jpg',
        		'title'=>'Top View Bar - Vanda Hotel',
        		'address'=>'03 Nguyễn Văn Linh, P. Bình Hiên,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-buffalo-bar-intercontinental-resort-da-nang.jpg',
        		'title'=>'Buffalo Bar - InterContinental Resort',
        		'address'=>'Bán Đảo Sơn Trà,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'drink',
                'img'=>'foody-mobile-477-jpg-554-636330532802270362.jpg',
        		'title'=>'Factory 47 Riverview',
        		'address'=>'28 Bạch Đằng,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'sheis-133b1734-53e4-4691-9caa-b10ea0788b8e-20170824100654535.jpg',
        		'title'=>'Queen Spa Đà Nẵng',
        		'address'=>'144 Phạm Cự Lượng,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-hre-jpg-163-636126368219046989.jpg',
        		'title'=>'Herbal Spa',
        		'address'=>'102 Dương Đình Nghệ,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-upload-api-foody-mobile-ng-linh-jpg-180516084515.jpg',
        		'title'=>'Ngọc Linh Spa',
        		'address'=>'233 Trần Phú, P. Phước Ninh,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-upload-api-foody-mobile-234-jpg-180313153656.jpg',
        		'title'=>'Sống Khỏe Spa',
        		'address'=>'229 Trần Phú, P. Phước Ninh,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-900x600-bic-spa-jpg-668-635935655378722709.jpg',
        		'title'=>'Yobel Spa',
        		'address'=>'35 Hải Phòng,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-17548515982_1154b199-995-635700480012634386.jpg',
        		'title'=>'Tắm Bùn Khoáng - Galina Da Nang Mud Bath & Spa',
        		'address'=>'28 Bạch Đằng,  Quận Hải Châu, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-foody-lua-spa-434-63-759-636070281009816643.jpg',
        		'title'=>'Lụa Spa',
        		'address'=>'153 Đỗ Quang,  Quận Thanh Khê, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-nam-jpg-597-636331139000940053.jpg',
        		'title'=>'Nam Hotel & Spa',
        		'address'=>'109A Dương Đình Nghệ, P. An Hải Bắc,  Quận Sơn Trà, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-like-jpg-425-636126359577532338.jpg',
        		'title'=>'Like Spa',
        		'address'=>'90 Hàm Nghi,  Quận Thanh Khê, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'relax',
                'img'=>'foody-mobile-mi-42-jpg-391-635935515038068214.jpg',
        		'title'=>'Miami Spa',
        		'address'=>'17 An Thượng 2, P. Mỹ An,  Quận Ngũ Hành Sơn, Đà Nẵng',
        		'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-m-chay-jpg-744-636319914265399781.jpg',
                'title'=>'Charm Lady',
                'address'=>'162 Lê Duẩn,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-wen-jpg.jpg',
                'title'=>'Wendy Story - Cửa Hàng Phụ Kiện',
                'address'=>'256 Phan Châu Trinh,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-upload-api-foody-mobile-ho-jpg-180516085451.jpg',
                'title'=>'Dana Watch - Đồng Hồ Chính Hãng',
                'address'=>'322 Trưng Nữ Vương,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-am-jpg.jpg',
                'title'=>'Yesterday Store - Shop Quần Áo Nam',
                'address'=>'91 Phan Thanh,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-men-jpg-426-636438385280325647.jpg',
                'title'=>'The Gmen Store - Thời Trang Nam',
                'address'=>'473 Hải Phòng,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-dia-jpg.jpg',
                'title'=>'>Myn Shoes',
                'address'=>'391 Lê Duẩn,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-ni-jpg-646-636438382503053245.jpg',
                'title'=>'Minigood Đà Nẵng',
                'address'=>'225 - 227 Nguyễn Văn Linh,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-2me-jpg-986-636089522014943919.jpg',
                'title'=>'Siêu Thị Metro',
                'address'=>'Cách Mạng Tháng 8,  Quận Cẩm Lệ, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-36-jpg-632-636365057721347024.jpg',
                'title'=>'Je Taime Shop',
                'address'=>'K22/7 Đào Duy Từ,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'buy',
                'img'=>'foody-mobile-dnang-jpg-710-635929441820570470.jpg',
                'title'=>'LOTTE Mart',
                'address'=>'6 Nại Nam, P. Hòa Cường Nam,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'Locked Danang (1).jpg',
                'title'=>"Locked Danang",
                'address'=>'270 Nguyễn Văn Linh,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'X8 Club Karaoke (1).jpg',
                'title'=>'X8 Club Karaoke',
                'address'=>'2 Ðinh Th? Hoà, Son trà, Ðà N?ng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-foody-vinpearlland-i-438-635726388964474070 (1).jpg',
                'title'=>'Vinpearlland Ice Rink - Vincom Center Đà Nẵng',
                'address'=>'Tầng 4, Vincom Center, 910A Ngô Quyền,  Quận Sơn Trà, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-bod-jpg.jpg',
                'title'=>'Boardgame Center',
                'address'=>'134 Nguyễn Đức Trung,  Quận Thanh Khê, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'Da Nang Water Sports (1).jpg',
                'title'=>'Da Nang Water Sports',
                'address'=>'Võ Nguyên Giáp, My Khe Beach, Ðà N?ng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-foody-khu-vui-choi-i-202-635639111645389275.jpg',
                'title'=>'Khu Vui Chơi Indochina - Bạch Đằng',
                'address'=>'Indochina Riverside Towers, 74 Bạch Đằng,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-game-2-jpg-201-635681663487796437.jpg',
                'title'=>'SpeedBowl - Thỏa Thích Vui Chơi',
                'address'=>'Parkson Hùng Vương,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-m-game-jpg-962-636281975251222964.jpg',
                'title'=>'>Da Nang Screen Golf',
                'address'=>'Tầng 3 - 4, Lô 01 - 02 Đinh Thị Hòa,  Quận Sơn Trà, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-foody-k97-gaming-ps4-227-635914763424983676.jpg',
                'title'=>'WE PES Game Lounge PS4',
                'address'=>'K254/3 Hoàng Diệu,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'entertainment',
                'img'=>'foody-mobile-c2-jpg-372-636016638164622268.jpg',
                'title'=>'Khu Vui Chơi Play Time - Lotte Mart Đà Nẵng',
                'address'=>'6 Nại Nam, P. Hòa Cường Bắc,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-gr-jpg-584-636322497469042354.jpg',
                'title'=>'Grand Mercure Danang',
                'address'=>'Lô A1, Khu Biệt Thự Đảo Xanh, P. Hòa Cường Bắc,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-sam6-jpg-208-635687657339533325.jpg',
                'title'=>'Samdi Hotel - Nguyễn Văn Linh',
                'address'=>'202 - 211 Nguyễn Văn Linh,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-1-2-jpg-635436055776796491.jpg',
                'title'=>'Minh Toàn Galaxy Hotel',
                'address'=>'306 Đường 2/9,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'2016330131646-2.jpg',
                'title'=>'Holiday Beach Danang Hotel & Resort',
                'address'=>'300 Võ Nguyên Giáp,  Quận Ngũ Hành Sơn, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-pullman-mb-jpg-310-635725138725203401.jpg',
                'title'=>'Pullman Danang Beach Resort',
                'address'=>'Võ Nguyên Giáp, P. Khuê Mỹ,  Quận Ngũ Hành Sơn, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-brilliant-hotel-da-nang-140620023222.jpg',
                'title'=>'Brilliant Hotel',
                'address'=>'162 Bạch Đằng,  Quận Hải Châu, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-c2-jpg-708-636113505369102904.jpg',
                'title'=>'Royal Lotus Hotel',
                'address'=>'120A Nguyễn Văn Thoại,  Quận Ngũ Hành Sơn, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-ava3-jpg-699-635797253930989248.jpg',
                'title'=>'Avatar Hotel',
                'address'=>'Lô 120 An Thượng 2, P. Mỹ An,  Quận Ngũ Hành Sơn, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-sup2-jpg-635436055831396587.jpg',
                'title'=>'Mường Thanh Đà Nẵng Hotel - Ngô Quyền',
                'address'=>'962 Ngô Quyền,  Quận Sơn Trà, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],
            [
                'filter'=>'stay',
                'img'=>'foody-mobile-golden-bay-jpg.jpg',
                'title'=>'Danang Golden Bay',
                'address'=>'1 Lê Văn Duyệt, P. Nại Hiên Đông,  Quận Sơn Trà, Đà Nẵng',
                'rating'=>'⭐⭐⭐⭐⭐',
            ],

        ]);
    }
}
